# mdck 開発設定
# 開発者向けの緩い設定

lint:
  rules:
    M002:
      enabled: true
      severity: warn
    M003:
      enabled: true
      severity: warn
    M004:
      enabled: true
      severity: error
  cache: true
  autoFix: true
  failOnWarning: false
  maxWarnings: 10

parser:
  templatePaths:
    - "./checklists/templates/**/*.md"
    - "../shared-templates/**/*.md"
    - "./examples/**/*.md"
  excludePatterns:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/.git/**"
  maxDepth: 15
  enableExternalReferences: true
  strictMode: false
  allowPartialTemplates: true

output:
  format: console
  color: true
  verbose: true
  quiet: false
  logLevel: debug

validation:
  requireMandatoryTags: false
  requireResultSections: false
  allowCustomItems: true
  enforceTagIds: false
  warnOnMissingResults: true

development:
  watchMode: true
  hotReload: true
  showPerformanceMetrics: true
  enableDebugMode: true

project:
  name: "Development Checklists (Dev Mode)"
  version: "1.0.0-dev"
  description: "Development-friendly configuration with relaxed rules"
  environment: development

cache: ./.mdck/.cache