# mdck 厳格設定
# CI/CD環境や本番環境向けの厳格な設定

lint:
  rules:
    M002:
      enabled: true
      severity: error
    M003:
      enabled: true
      severity: error
    M004:
      enabled: true
      severity: error
  cache: true
  autoFix: false
  failOnWarning: true
  maxWarnings: 0

parser:
  templatePaths:
    - "./checklists/templates/**/*.md"
  excludePatterns:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/.git/**"
    - "**/tmp_*"
    - "**/.*"
  maxDepth: 5
  enableExternalReferences: false
  strictMode: true

output:
  format: json
  color: false
  verbose: true
  quiet: false
  logLevel: info

validation:
  requireMandatoryTags: true
  requireResultSections: true
  allowCustomItems: false
  enforceTagIds: true

project:
  name: "Development Checklists (Strict Mode)"
  version: "1.0.0"
  description: "Strict configuration for CI/CD environments"
  environment: production

cache: ./.mdck/.cache